// src/components/common/EmptyState.tsx
import React, { ReactNode } from 'react';

interface EmptyStateAction {
  label: string;
  onClick: () => void;
}

interface EmptyStateProps {
  title: string;
  description: string;
  icon: ReactNode;
  action?: EmptyStateAction;
}

const EmptyState: React.FC<EmptyStateProps> = ({
  title,
  description,
  icon,
  action
}) => {
  return (
    <div className="bg-white rounded-lg shadow-sm p-8 border border-gray-100 text-center">
      <div className="flex justify-center mb-4">
        {icon}
      </div>
      <h3 className="text-lg font-medium text-gray-900 mb-2">{title}</h3>
      <p className="text-gray-500 mb-6">{description}</p>
      
      {action && (
        <button
          onClick={action.onClick}
          className="px-4 py-2 bg-emerald-600 text-white rounded-md hover:bg-emerald-700 transition-colors inline-flex items-center justify-center"
        >
          {action.label}
        </button>
      )}
    </div>
  );
};

export default EmptyState;

// src/components/common/EmptyState.vue
<template>
  <div class="text-center py-12 px-4">
    <div 
      class="inline-flex items-center justify-center w-16 h-16 rounded-full bg-gray-100 text-gray-500 mb-4"
    >
      <component :is="icon" class="w-8 h-8" />
    </div>
    <h3 class="text-lg font-medium text-gray-900 mb-2">{{ title }}</h3>
    <p class="text-gray-500 max-w-sm mx-auto mb-6">{{ description }}</p>
    <slot name="action">
      <button
        v-if="action"
        @click="action.onClick"
        class="btn-primary inline-flex items-center"
      >
        <component :is="action.icon" v-if="action.icon" class="w-4 h-4 mr-2" />
        {{ action.label }}
      </button>
    </slot>
  </div>
</template>

<script setup lang="ts">
import type { Component } from 'vue';

interface Action {
  label: string;
  onClick: () => void;
  icon?: Component;
}

defineProps<{
  title: string;
  description: string;
  icon: Component;
  action?: Action;
}>();
</script>
